FROM chronograf:latest

COPY ./chronograf.conf /etc/chronograf/chronograf.conf

ENV INFLUXDB_DB=cdndb
ENV INFLUXDB_ADMIN_USER=admin
ENV INFLUXDB_ADMIN_PASSWORD=admin
ENV INFLUXDB_HTTP_AUTH_ENABLED=true
ENV INFLUXDB_HTTP_FLUX_ENABLED=true

EXPOSE 8888

CMD ["chronograf"]