version: '3'

services:
  nginx: 
    build: ./Backend/nginx
    depends_on:
      - influxdb
      - springboot
    ports:
      - "80:80"
  springboot:
    build: ./Backend/springboot
    depends_on:
      - influxdb
  influxdb:
    build: ./Backend/influxDB
    ports:
      - "8086:8086"
      - "8088:8088"

  # chronograf:
  #   build: ./Backend/chronograf
  #   ports:
  #     - "8888:8888"

  # kapacitor:
  #   build: ./Backend/kapacitor
  #   ports:
  #     - "9092:9092"