version: '3'

services:
  nginx: 
    build: ./Backend/nginx
    container_name: nginx
    depends_on:
      - influxdb
      - springboot
    ports:
      - "80:80"
    networks:
      - default
  springboot:
    container_name: springboot
    build: ./Backend/springboot
    depends_on:
      - influxdb
      - mosquitto
    ports:
      - "8080:8080"
    networks:
      - default
  influxdb:
    build: ./Backend/influxDB
    container_name: influxdb
    depends_on:
      - chronograf
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8088:8088"
    networks:
      - default
  chronograf:
    build: ./Backend/chronograf
    container_name: chronograf
    ports:
      - "8888:8888"
    networks:
      - default
  mosquitto:
    build: ./Backend/mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - default

networks:
  default:
    driver: bridge