version: '3'

services:
  nginx: 
    build: ./nginx
    depends_on:
      - influxdb
      - springboot
    ports:
      - "80:80"
  springboot:
    build: ./springboot
    depends_on:
      - influxdb
  influxdb:
    build: ./influxDB
  