version: '3'

services:
  nginx: 
    build: ./Backend/nginx
    depends_on:
      - influxdb
      - springboot
    ports:
      - "80:80"
  springboot:
    build: ./Backend/springboot
    depends_on:
      - influxdb
  influxdb:
    build: ./Backend/influxDB
  