FROM influxdb:latest

EXPOSE 8086
EXPOSE 8088
EXPOSE 8083

ENV DOCKER_INFLUXDB_INIT_MODE=setup
ENV DOCKER_INFLUXDB_INIT_USERNAME=admin
ENV DOCKER_INFLUXDB_INIT_PASSWORD=admin12345
ENV DOCKER_INFLUXDB_INIT_ORG=UCU
ENV DOCKER_INFLUXDB_INIT_BUCKET=DATA
ENV DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=0qfrVjTKP-s9VZ_msUoZqez5ubytxENzCZo93WNE1_rzI-2k59tTLcRTMHCsWlxm67paxbCKInl0b8HzG5PzLg==
ENV INFLUXD_HTTP_BIND_ADDRESS=:8086
ENV INFLUXD_API_BIND_ADDRESS=:8086

VOLUME [ "/var/lib/influxdb2" ]


CMD ["influxd"]


#RUN curl --request POST \
# "http://localhost:8086/api/v2/buckets" \
# --header "Authorization: Token ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}" \
# --header "Content-type: application/json" \
# --data '{ \
#   "orgID": "'"${DOCKER_INFLUXDB_INIT_ORG}"'", \
#   "name": "temperatures", \
#   "retentionRules": [ \
#     { \
#       "type": "expire", \
#       "everySeconds": 604800, \
#       "shardGroupDurationSeconds": 0 \
#     } \
#   ] \
# }'
#RUN curl --request POST \
#  "http://localhost:8086/api/v2/buckets" \
#  --header "Authorization: Token ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}" \
#  --header "Content-type: application/json" \
#  --data '{ \
#    "orgID": "'"${DOCKER_INFLUXDB_INIT_ORG}"'", \
#    "name": "humidities", \
#    "retentionRules": [ \
#      { \
#        "type": "expire", \
#        "everySeconds": 604800, \
#        "shardGroupDurationSeconds": 0 \
#      } \
#    ] \
#  }'

#RUN influx bucket create -n humidities -r 1w -o UCU