FROM node:13.12.0-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
ENV CHOKIDAR_USEPOLLING=true

COPY . ./
RUN npm install react-scripts@3.4.1 -g --silent
RUN npm install --legacy-peer-deps

EXPOSE 3000


CMD ["npm", "run", "start"]

VOLUME [ "/app/node_modules" ]