FROM influxdb:latest

COPY init-DB.sql /etc/influxdb/init-DB.sql
COPY influxdb.conf /etc/influxdb/influxdb.conf

EXPOSE 8086

COPY ./init-DB.sql /etc/influxdb2/init-DB.sql
COPY ./influxdb.conf /etc/influxdb2/influxdb.conf
CMD ["influxd"]