FROM kapacitor:latest

COPY ./kapacitor.conf /etc/kapacitor/kapacitor.conf

ENV INFLUXDB_URL=http://influxdb:8086
ENV INFLUXDB_DB=cdndb
ENV INFLUXDB_USERNAME=admin
ENV INFLUXDB_PASSWORD=admin

EXPOSE 9092

CMD ["kapacitor", "-config", "/etc/kapacitor/kapacitor.conf"]